Previewing update (super)

View Live: https://app.pulumi.com/pulumi-account/super-pulumi/super/previews/6b62c057-eade-41b2-a28e-74976777b18b


    pulumi:pulumi:Stack super-pulumi-super running 
    pulumi:pulumi:Stack super-pulumi-super running qz9jMiN-wrXqpj&
    pulumi:pulumi:Stack super-pulumi-super running Error: Resource monitor is terminating
    pulumi:pulumi:Stack super-pulumi-super running     at Object.callErrorFromStatus (/Users/alexwoods/experiments/super-pulumi/node_modules/@grpc/grpc-js/src/call.ts:81:24)
    pulumi:pulumi:Stack super-pulumi-super running     at Object.onReceiveStatus (/Users/alexwoods/experiments/super-pulumi/node_modules/@grpc/grpc-js/src/client.ts:334:36)
    pulumi:pulumi:Stack super-pulumi-super running     at Object.onReceiveStatus (/Users/alexwoods/experiments/super-pulumi/node_modules/@grpc/grpc-js/src/client-interceptors.ts:426:34)
    pulumi:pulumi:Stack super-pulumi-super running     at Object.onReceiveStatus (/Users/alexwoods/experiments/super-pulumi/node_modules/@grpc/grpc-js/src/client-interceptors.ts:389:48)
    pulumi:pulumi:Stack super-pulumi-super running     at process.nextTick (/Users/alexwoods/experiments/super-pulumi/node_modules/@grpc/grpc-js/src/call-stream.ts:276:24)
    pulumi:pulumi:Stack super-pulumi-super running     at process.internalTickCallback (internal/process/next_tick.js:70:11)
    pulumi:pulumi:Stack super-pulumi-super running unhandled rejection: CONTEXT(28): monitor.registerResourceOutputs(...)-initial
    pulumi:pulumi:Stack super-pulumi-super running STACK_TRACE:
    pulumi:pulumi:Stack super-pulumi-super running Error
    pulumi:pulumi:Stack super-pulumi-super running     at Object.debuggablePromise (/Users/alexwoods/experiments/super-pulumi/node_modules/@pulumi/pulumi/runtime/debuggable.js:69:75)
    pulumi:pulumi:Stack super-pulumi-super running     at runAsyncResourceOp (/Users/alexwoods/experiments/super-pulumi/node_modules/@pulumi/pulumi/runtime/resource.js:681:75)
    pulumi:pulumi:Stack super-pulumi-super running     at Object.registerResourceOutputs (/Users/alexwoods/experiments/super-pulumi/node_modules/@pulumi/pulumi/runtime/resource.js:600:5)
    pulumi:pulumi:Stack super-pulumi-super running     at Stack.registerOutputs (/Users/alexwoods/experiments/super-pulumi/node_modules/@pulumi/pulumi/resource.js:444:20)
    pulumi:pulumi:Stack super-pulumi-super running     at Stack.<anonymous> (/Users/alexwoods/experiments/super-pulumi/node_modules/@pulumi/pulumi/runtime/stack.js:94:40)
    pulumi:pulumi:Stack super-pulumi-super running     at Generator.next (<anonymous>)
    pulumi:pulumi:Stack super-pulumi-super running     at fulfilled (/Users/alexwoods/experiments/super-pulumi/node_modules/@pulumi/pulumi/runtime/stack.js:18:58)
    pulumi:pulumi:Stack super-pulumi-super running     at process.internalTickCallback (internal/process/next_tick.js:77:7)
    pulumi:pulumi:Stack super-pulumi-super running error: [runtime] Running program '/Users/alexwoods/experiments/super-pulumi' failed with an unhandled exception:
    pulumi:pulumi:Stack super-pulumi-super running Error: Resource monitor is terminating
    pulumi:pulumi:Stack super-pulumi-super running     at Object.callErrorFromStatus (/Users/alexwoods/experiments/super-pulumi/node_modules/@grpc/grpc-js/src/call.ts:81:24)
    pulumi:pulumi:Stack super-pulumi-super running     at Object.onReceiveStatus (/Users/alexwoods/experiments/super-pulumi/node_modules/@grpc/grpc-js/src/client.ts:334:36)
    pulumi:pulumi:Stack super-pulumi-super running     at Object.onReceiveStatus (/Users/alexwoods/experiments/super-pulumi/node_modules/@grpc/grpc-js/src/client-interceptors.ts:426:34)
    pulumi:pulumi:Stack super-pulumi-super running     at Object.onReceiveStatus (/Users/alexwoods/experiments/super-pulumi/node_modules/@grpc/grpc-js/src/client-interceptors.ts:389:48)
    pulumi:pulumi:Stack super-pulumi-super running     at process.nextTick (/Users/alexwoods/experiments/super-pulumi/node_modules/@grpc/grpc-js/src/call-stream.ts:276:24)
    pulumi:pulumi:Stack super-pulumi-super running     at process.internalTickCallback (internal/process/next_tick.js:70:11)
    pulumi:pulumi:Stack super-pulumi-super running unhandled rejection: CONTEXT(28): monitor.registerResourceOutputs(...)-initial
    pulumi:pulumi:Stack super-pulumi-super running STACK_TRACE:
    pulumi:pulumi:Stack super-pulumi-super running Error
    pulumi:pulumi:Stack super-pulumi-super running     at Object.debuggablePromise (/Users/alexwoods/experiments/super-pulumi/node_modules/@pulumi/pulumi/runtime/debuggable.js:69:75)
    pulumi:pulumi:Stack super-pulumi-super running     at runAsyncResourceOp (/Users/alexwoods/experiments/super-pulumi/node_modules/@pulumi/pulumi/runtime/resource.js:681:75)
    pulumi:pulumi:Stack super-pulumi-super running     at Object.registerResourceOutputs (/Users/alexwoods/experiments/super-pulumi/node_modules/@pulumi/pulumi/runtime/resource.js:600:5)
    pulumi:pulumi:Stack super-pulumi-super running     at Stack.registerOutputs (/Users/alexwoods/experiments/super-pulumi/node_modules/@pulumi/pulumi/resource.js:444:20)
    pulumi:pulumi:Stack super-pulumi-super running     at Stack.<anonymous> (/Users/alexwoods/experiments/super-pulumi/node_modules/@pulumi/pulumi/runtime/stack.js:94:40)
    pulumi:pulumi:Stack super-pulumi-super running     at Generator.next (<anonymous>)
    pulumi:pulumi:Stack super-pulumi-super running     at fulfilled (/Users/alexwoods/experiments/super-pulumi/node_modules/@pulumi/pulumi/runtime/stack.js:18:58)
    pulumi:pulumi:Stack super-pulumi-super running     at process.internalTickCallback (internal/process/next_tick.js:77:7)
    pulumi:pulumi:Stack super-pulumi-super running CommandError: code: 255
    pulumi:pulumi:Stack super-pulumi-super running  stdout: Updating (dev)
    pulumi:pulumi:Stack super-pulumi-super running View Live: https://app.pulumi.com/pulumi-account/sub-a/dev/updates/5
    pulumi:pulumi:Stack super-pulumi-super running     pulumi:pulumi:Stack sub-a-dev running 
    pulumi:pulumi:Stack super-pulumi-super running     random:index:RandomString sub-a  
    pulumi:pulumi:Stack super-pulumi-super running     pulumi:pulumi:Stack sub-a-dev running error: resource complete event returned an error: failed to verify snapshot: child resource urn:pulumi:dev::sub-a::random:index/randomString:RandomString::sub-a refers to missing parent urn:pulumi:super::super-pulumi::pulumi:pulumi:Stack::super-pulumi-super
    pulumi:pulumi:Stack super-pulumi-super running     pulumi:pulumi:Stack sub-a-dev running error: update failed
    pulumi:pulumi:Stack super-pulumi-super running     pulumi:pulumi:Stack sub-a-dev **failed** 2 errors
    pulumi:pulumi:Stack super-pulumi-super running Diagnostics:
    pulumi:pulumi:Stack super-pulumi-super running   pulumi:pulumi:Stack (sub-a-dev):
    pulumi:pulumi:Stack super-pulumi-super running     error: resource complete event returned an error: failed to verify snapshot: child resource urn:pulumi:dev::sub-a::random:index/randomString:RandomString::sub-a refers to missing parent urn:pulumi:super::super-pulumi::pulumi:pulumi:Stack::super-pulumi-super
    pulumi:pulumi:Stack super-pulumi-super running     error: update failed
    pulumi:pulumi:Stack super-pulumi-super running Outputs:
    pulumi:pulumi:Stack super-pulumi-super running   + result: "qz9jMiN-wrXqpj&"
    pulumi:pulumi:Stack super-pulumi-super running Resources:
    pulumi:pulumi:Stack super-pulumi-super running     2 unchanged
    pulumi:pulumi:Stack super-pulumi-super running Duration: 1s
    pulumi:pulumi:Stack super-pulumi-super running  stderr: 
    pulumi:pulumi:Stack super-pulumi-super running  err?: 
    pulumi:pulumi:Stack super-pulumi-super running     at Object.createCommandError (/Users/alexwoods/experiments/super-pulumi/node_modules/@pulumi/pulumi/automation/errors.js:71:17)
    pulumi:pulumi:Stack super-pulumi-super running     at ChildProcess.proc.on (/Users/alexwoods/experiments/super-pulumi/node_modules/@pulumi/pulumi/automation/cmd.js:63:40)
    pulumi:pulumi:Stack super-pulumi-super running     at ChildProcess.emit (events.js:188:13)
    pulumi:pulumi:Stack super-pulumi-super running     at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
    pulumi:pulumi:Stack super-pulumi-super running error: [runtime] Running program '/Users/alexwoods/experiments/super-pulumi' failed with an unhandled exception:
    pulumi:pulumi:Stack super-pulumi-super running CommandError: code: 255
    pulumi:pulumi:Stack super-pulumi-super running  stdout: Updating (dev)
    pulumi:pulumi:Stack super-pulumi-super running View Live: https://app.pulumi.com/pulumi-account/sub-a/dev/updates/5
    pulumi:pulumi:Stack super-pulumi-super running     pulumi:pulumi:Stack sub-a-dev running 
    pulumi:pulumi:Stack super-pulumi-super running     random:index:RandomString sub-a  
    pulumi:pulumi:Stack super-pulumi-super running     pulumi:pulumi:Stack sub-a-dev running error: resource complete event returned an error: failed to verify snapshot: child resource urn:pulumi:dev::sub-a::random:index/randomString:RandomString::sub-a refers to missing parent urn:pulumi:super::super-pulumi::pulumi:pulumi:Stack::super-pulumi-super
    pulumi:pulumi:Stack super-pulumi-super running     pulumi:pulumi:Stack sub-a-dev running error: update failed
    pulumi:pulumi:Stack super-pulumi-super running     pulumi:pulumi:Stack sub-a-dev **failed** 2 errors
    pulumi:pulumi:Stack super-pulumi-super running Diagnostics:
    pulumi:pulumi:Stack super-pulumi-super running   pulumi:pulumi:Stack (sub-a-dev):
    pulumi:pulumi:Stack super-pulumi-super running     error: resource complete event returned an error: failed to verify snapshot: child resource urn:pulumi:dev::sub-a::random:index/randomString:RandomString::sub-a refers to missing parent urn:pulumi:super::super-pulumi::pulumi:pulumi:Stack::super-pulumi-super
    pulumi:pulumi:Stack super-pulumi-super running     error: update failed
    pulumi:pulumi:Stack super-pulumi-super running Outputs:
    pulumi:pulumi:Stack super-pulumi-super running   + result: "qz9jMiN-wrXqpj&"
    pulumi:pulumi:Stack super-pulumi-super running Resources:
    pulumi:pulumi:Stack super-pulumi-super running     2 unchanged
    pulumi:pulumi:Stack super-pulumi-super running Duration: 1s
    pulumi:pulumi:Stack super-pulumi-super running  stderr: 
    pulumi:pulumi:Stack super-pulumi-super running  err?: 
    pulumi:pulumi:Stack super-pulumi-super running     at Object.createCommandError (/Users/alexwoods/experiments/super-pulumi/node_modules/@pulumi/pulumi/automation/errors.js:71:17)
    pulumi:pulumi:Stack super-pulumi-super running     at ChildProcess.proc.on (/Users/alexwoods/experiments/super-pulumi/node_modules/@pulumi/pulumi/automation/cmd.js:63:40)
    pulumi:pulumi:Stack super-pulumi-super running     at ChildProcess.emit (events.js:188:13)
    pulumi:pulumi:Stack super-pulumi-super running     at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
    pulumi:pulumi:Stack super-pulumi-super  85 messages
 
Diagnostics:
  pulumi:pulumi:Stack (super-pulumi-super):
    qz9jMiN-wrXqpj&
    unhandled rejection: CONTEXT(28): monitor.registerResourceOutputs(...)-initial
    STACK_TRACE:
    Error
        at Object.debuggablePromise (/Users/alexwoods/experiments/super-pulumi/node_modules/@pulumi/pulumi/runtime/debuggable.js:69:75)
        at runAsyncResourceOp (/Users/alexwoods/experiments/super-pulumi/node_modules/@pulumi/pulumi/runtime/resource.js:681:75)
        at Object.registerResourceOutputs (/Users/alexwoods/experiments/super-pulumi/node_modules/@pulumi/pulumi/runtime/resource.js:600:5)
        at Stack.registerOutputs (/Users/alexwoods/experiments/super-pulumi/node_modules/@pulumi/pulumi/resource.js:444:20)
        at Stack.<anonymous> (/Users/alexwoods/experiments/super-pulumi/node_modules/@pulumi/pulumi/runtime/stack.js:94:40)
        at Generator.next (<anonymous>)
        at fulfilled (/Users/alexwoods/experiments/super-pulumi/node_modules/@pulumi/pulumi/runtime/stack.js:18:58)
        at process.internalTickCallback (internal/process/next_tick.js:77:7)
    unhandled rejection: CONTEXT(28): monitor.registerResourceOutputs(...)-initial
    STACK_TRACE:
    Error
        at Object.debuggablePromise (/Users/alexwoods/experiments/super-pulumi/node_modules/@pulumi/pulumi/runtime/debuggable.js:69:75)
        at runAsyncResourceOp (/Users/alexwoods/experiments/super-pulumi/node_modules/@pulumi/pulumi/runtime/resource.js:681:75)
        at Object.registerResourceOutputs (/Users/alexwoods/experiments/super-pulumi/node_modules/@pulumi/pulumi/runtime/resource.js:600:5)
        at Stack.registerOutputs (/Users/alexwoods/experiments/super-pulumi/node_modules/@pulumi/pulumi/resource.js:444:20)
        at Stack.<anonymous> (/Users/alexwoods/experiments/super-pulumi/node_modules/@pulumi/pulumi/runtime/stack.js:94:40)
        at Generator.next (<anonymous>)
        at fulfilled (/Users/alexwoods/experiments/super-pulumi/node_modules/@pulumi/pulumi/runtime/stack.js:18:58)
        at process.internalTickCallback (internal/process/next_tick.js:77:7)
 
    Error: Resource monitor is terminating
        at Object.callErrorFromStatus (/Users/alexwoods/experiments/super-pulumi/node_modules/@grpc/grpc-js/src/call.ts:81:24)
        at Object.onReceiveStatus (/Users/alexwoods/experiments/super-pulumi/node_modules/@grpc/grpc-js/src/client.ts:334:36)
        at Object.onReceiveStatus (/Users/alexwoods/experiments/super-pulumi/node_modules/@grpc/grpc-js/src/client-interceptors.ts:426:34)
        at Object.onReceiveStatus (/Users/alexwoods/experiments/super-pulumi/node_modules/@grpc/grpc-js/src/client-interceptors.ts:389:48)
        at process.nextTick (/Users/alexwoods/experiments/super-pulumi/node_modules/@grpc/grpc-js/src/call-stream.ts:276:24)
        at process.internalTickCallback (internal/process/next_tick.js:70:11)
    error: [runtime] Running program '/Users/alexwoods/experiments/super-pulumi' failed with an unhandled exception:
    Error: Resource monitor is terminating
        at Object.callErrorFromStatus (/Users/alexwoods/experiments/super-pulumi/node_modules/@grpc/grpc-js/src/call.ts:81:24)
        at Object.onReceiveStatus (/Users/alexwoods/experiments/super-pulumi/node_modules/@grpc/grpc-js/src/client.ts:334:36)
        at Object.onReceiveStatus (/Users/alexwoods/experiments/super-pulumi/node_modules/@grpc/grpc-js/src/client-interceptors.ts:426:34)
        at Object.onReceiveStatus (/Users/alexwoods/experiments/super-pulumi/node_modules/@grpc/grpc-js/src/client-interceptors.ts:389:48)
        at process.nextTick (/Users/alexwoods/experiments/super-pulumi/node_modules/@grpc/grpc-js/src/call-stream.ts:276:24)
        at process.internalTickCallback (internal/process/next_tick.js:70:11)
    CommandError: code: 255
     stdout: Updating (dev)
    View Live: https://app.pulumi.com/pulumi-account/sub-a/dev/updates/5
        pulumi:pulumi:Stack sub-a-dev running
        random:index:RandomString sub-a
        pulumi:pulumi:Stack sub-a-dev running error: resource complete event returned an error: failed to verify snapshot: child resource urn:pulumi:dev::sub-a::random:index/randomString:RandomString::sub-a refers to missing parent urn:pulumi:super::super-pulumi::pulumi:pulumi:Stack::super-pulumi-super
        pulumi:pulumi:Stack sub-a-dev running error: update failed
        pulumi:pulumi:Stack sub-a-dev **failed** 2 errors
    Diagnostics:
      pulumi:pulumi:Stack (sub-a-dev):
        error: resource complete event returned an error: failed to verify snapshot: child resource urn:pulumi:dev::sub-a::random:index/randomString:RandomString::sub-a refers to missing parent urn:pulumi:super::super-pulumi::pulumi:pulumi:Stack::super-pulumi-super
        error: update failed
    Outputs:
      + result: "qz9jMiN-wrXqpj&"
    Resources:
        2 unchanged
    Duration: 1s
     stderr:
     err?:
        at Object.createCommandError (/Users/alexwoods/experiments/super-pulumi/node_modules/@pulumi/pulumi/automation/errors.js:71:17)
        at ChildProcess.proc.on (/Users/alexwoods/experiments/super-pulumi/node_modules/@pulumi/pulumi/automation/cmd.js:63:40)
        at ChildProcess.emit (events.js:188:13)
        at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
    error: [runtime] Running program '/Users/alexwoods/experiments/super-pulumi' failed with an unhandled exception:
    CommandError: code: 255
     stdout: Updating (dev)
    View Live: https://app.pulumi.com/pulumi-account/sub-a/dev/updates/5
        pulumi:pulumi:Stack sub-a-dev running
        random:index:RandomString sub-a
        pulumi:pulumi:Stack sub-a-dev running error: resource complete event returned an error: failed to verify snapshot: child resource urn:pulumi:dev::sub-a::random:index/randomString:RandomString::sub-a refers to missing parent urn:pulumi:super::super-pulumi::pulumi:pulumi:Stack::super-pulumi-super
        pulumi:pulumi:Stack sub-a-dev running error: update failed
        pulumi:pulumi:Stack sub-a-dev **failed** 2 errors
    Diagnostics:
      pulumi:pulumi:Stack (sub-a-dev):
        error: resource complete event returned an error: failed to verify snapshot: child resource urn:pulumi:dev::sub-a::random:index/randomString:RandomString::sub-a refers to missing parent urn:pulumi:super::super-pulumi::pulumi:pulumi:Stack::super-pulumi-super
        error: update failed
    Outputs:
      + result: "qz9jMiN-wrXqpj&"
    Resources:
        2 unchanged
    Duration: 1s
     stderr:
     err?:
        at Object.createCommandError (/Users/alexwoods/experiments/super-pulumi/node_modules/@pulumi/pulumi/automation/errors.js:71:17)
        at ChildProcess.proc.on (/Users/alexwoods/experiments/super-pulumi/node_modules/@pulumi/pulumi/automation/cmd.js:63:40)
        at ChildProcess.emit (events.js:188:13)
        at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
 
Outputs:
  - default: {}


